### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by niftylettuce** [unshiftio/url-parse#147]
I receive the following error after this line is used:

```js
// inspired from `preserve-qs` package
let originalUrl = '';
if (isString(req.originalUrl)) ({ originalUrl } = req);
else if (isString(req.url)) originalUrl = req.url;
else if (hasWindow)
  originalUrl = window.location.pathname + window.location.search;
                                                                   
originalUrl = new URLParse(originalUrl); // <--- ERROR OCCURS HERE
```

```sh
  RangeError: Maximum call stack size exceeded
      at RegExp.exec (<anonymous>)
      at extractProtocol (/Users/user/Projects/project/node_modules/url-parse/index.js:95:26)
      at new URL (/Users/user/Projects/project/node_modules/url-parse/index.js:183:15)
      at parseRequest (/Users/user/Projects/project/node_modules/parse-request/src/index.js:32:17)
      at Project.ctx.logger.(anonymous function) [as warn] (/Users/user/Projects/project/src/index.js:98:11)
      at Project.ctx.logger.(anonymous function) [as warn] (/Users/user/Projects/project/src/index.js:101:9)
      at Project.ctx.logger.(anonymous function) [as warn] (/Users/user/Projects/project/src/index.js:101:9)
      at Project.ctx.logger.(anonymous function) [as warn] (/Users/user/Projects/project/src/index.js:101:9)
      at Project.ctx.logger.(anonymous function) [as warn] (/Users/user/Projects/project/src/index.js:101:9)
      at Project.ctx.logger.(anonymous function) [as warn] (/Users/user/Projects/project/src/index.js:101:9)
```

**Comment by 3rd-Eden** [comment]
@niftylettuce I see you closed this issue, but do you have the `originalUrl` that caused the regexp to blow up?

**Comment by niftylettuce** [comment]
I don't anymore - if it comes up again I'll let you know
